from __future__ import annotations

import cv2
import numpy as np

from ..config import RegistrationConfig
from ..preprocess import resize_for_matching
from ..types import MatchSet


class SIFTMatcher:
    name = "sift"

    def __init__(self, config: RegistrationConfig):
        self.config = config
        self.detector = cv2.SIFT_create(
            nfeatures=config.sift_features,
            contrastThreshold=config.sift_contrast_threshold,
            edgeThreshold=config.sift_edge_threshold,
            sigma=1.6,
        )

    @staticmethod
    def _mutual_ratio_matches(desc0: np.ndarray, desc1: np.ndarray, ratio: float, mutual: bool):
        matcher = cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)
        forward = matcher.knnMatch(desc0, desc1, k=2)
        reverse_best: dict[int, int] = {}
        if mutual:
            reverse = matcher.knnMatch(desc1, desc0, k=2)
            for pair in reverse:
                if len(pair) == 2 and pair[0].distance < ratio * pair[1].distance:
                    reverse_best[pair[0].queryIdx] = pair[0].trainIdx

        accepted = []
        for pair in forward:
            if len(pair) != 2:
                continue
            best, second = pair
            if best.distance >= ratio * second.distance:
                continue
            if mutual and reverse_best.get(best.trainIdx) != best.queryIdx:
                continue
            confidence = float(max(0.0, 1.0 - best.distance / (second.distance + 1e-8)))
            accepted.append((best.queryIdx, best.trainIdx, confidence))
        return accepted

    def match(self, source_views: dict[str, np.ndarray], reference_views: dict[str, np.ndarray]) -> MatchSet:
        all_records: list[tuple[float, float, float, float, float, str]] = []
        for label in sorted(set(source_views) & set(reference_views)):
            source, source_sx, source_sy = resize_for_matching(source_views[label], self.config.max_dimension)
            reference, reference_sx, reference_sy = resize_for_matching(
                reference_views[label], self.config.max_dimension
            )
            key0, desc0 = self.detector.detectAndCompute(source, None)
            key1, desc1 = self.detector.detectAndCompute(reference, None)
            if desc0 is None or desc1 is None or len(key0) < 2 or len(key1) < 2:
                continue
            matches = self._mutual_ratio_matches(
                desc0,
                desc1,
                ratio=self.config.ratio_test,
                mutual=self.config.require_mutual,
            )
            for idx0, idx1, confidence in matches:
                x0, y0 = key0[idx0].pt
                x1, y1 = key1[idx1].pt
                all_records.append(
                    (
                        x0 / source_sx,
                        y0 / source_sy,
                        x1 / reference_sx,
                        y1 / reference_sy,
                        confidence,
                        label,
                    )
                )

        if not all_records:
            return MatchSet(
                np.empty((0, 2), dtype=np.float32),
                np.empty((0, 2), dtype=np.float32),
                np.empty((0,), dtype=np.float32),
                np.empty((0,), dtype=object),
            )

        # Deduplicate matches generated by multiple image representations.
        best_by_location: dict[tuple[int, int, int, int], tuple[float, float, float, float, float, str]] = {}
        for record in all_records:
            key = tuple(round(value / 1.5) for value in record[:4])
            if key not in best_by_location or record[4] > best_by_location[key][4]:
                best_by_location[key] = record
        records = sorted(best_by_location.values(), key=lambda row: row[4], reverse=True)
        source_points = np.asarray([[row[0], row[1]] for row in records], dtype=np.float32)
        reference_points = np.asarray([[row[2], row[3]] for row in records], dtype=np.float32)
        scores = np.asarray([row[4] for row in records], dtype=np.float32)
        labels = np.asarray([row[5] for row in records], dtype=object)
        return MatchSet(source_points, reference_points, scores, labels)
